User_agent: okCupid
city: Manhattan
host: https://www.okcupid.com/login
url_match: https://www.okcupid.com/match
url_traverse: https://www.okcupid.com
name: Anjana
username: aj.goldfish@gmail.com
password: rInwu9-giqvaw-viqnin
output_folder: "/output/"
pincode: 10001
country_name: US
backfill: False
backfill_folder: '/output/images/'
reloads: 10
pause: 5