User_agent: Tinder/10.13.0 (iPhone; iOS 12.2.0; Scale/2.00)
app_version: 10.13.0
city: Berkeley
gender: 1
gender_filter: 0
host: https://api.gotinder.com
max_age: 25
min_age: 18
name: Aayushi
output_folder: "../../../output/"
cleaned_output: "../../../cleaned_output/"
ph_user_agent: Mozilla/5.0 (iPhone; CPU iPhone OS 11_2_5 like Mac OS X) AppleWebKit/604.5.6
  (KHTML, like Gecko) Mobile/15D60 AKiOSSDK/4.29.0
platform: ios
right_swipes: 20
tinder_token: 87fb3dfb-8748-4d16-b3d1-45ab26fa8262
pincode: 94720
country_name: US
backfill: False
backfill_folder: '../../../output/Berkley/images/2019-06-04'