User_agent: Tinder/10.17.0 (BND-AL10; Android 8.0.0; Scale/2.00)
app_version: 10.17.0
city: Delhi
gender: 0
gender_filter: 1
host: https://api.gotinder.com
max_age: 40
min_age: 18
name: Kashish
output_folder: '../../../output/'
ph_user_agent: Mozilla/5.0 (iPhone; CPU iPhone OS 11_2_5 like Mac OS X) AppleWebKit/604.5.6
  (KHTML, like Gecko) Mobile/15D60 AKiOSSDK/4.29.0
platform: Android
right_swipes: 20
tinder_token: ee9882fc-4890-4719-80f3-30775b419101
pincode: 110018
country_name: IN
backfill: False
backfill_folder: '../../../output/Delhi/images/2019-06-01'