User_agent: Tinder/10.13.0 (iPhone; iOS 12.2.0; Scale/2.00)
app_version: 10.13.0
city: Boston
gender: 0
gender_filter: 1
host: https://api.gotinder.com
max_age: 25
min_age: 18
name: Pallavi
output_folder: '../../../output/'
ph_user_agent: Mozilla/5.0 (iPhone; CPU iPhone OS 11_2_5 like Mac OS X) AppleWebKit/604.5.6
  (KHTML, like Gecko) Mobile/15D60 AKiOSSDK/4.29.0
platform: ios
right_swipes: 1
tinder_token: f3fa027f-f084-4891-b82e-889ec93cf436
pincode: 02138
country_name: US
backfill: False
backfill_folder: '../../../output/Boston/images/2019-06-01'
